repository: slater-brian-john/slater-brian-john.github.io
title: John Brian Slater
description: Software Engineer, Technical Architect, Co-Founder
remote_theme: pages-themes/midnight@v0.2.0
hide_site_feed_link: true
show_downloads: false


plugins:
  - jekyll-remote-theme
  - jekyll-feed

# test