title: John Brian Slater
description: Software Engineer, Technical Architect, Co-Founder
remote_theme: pages-themes/minimal@v0.2.0
hide_site_feed_link: true
show_downloads: true


plugins:
  - jekyll-remote-theme
  - jekyll-feed

