title: John Brian Slater
description: Software Engineer, Technical Architect, Co-Founder
remote_theme: "jekyll/minima@1e8a445"
theme: minima
minima:
  skin: dark
  author:
    name: John Brian Slater
    email: "slater@fivestar.studio
  hide_site_feed_link: true
  show_downloads: true


plugins:
  - jekyll-remote-theme
  - jekyll-feed

